// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3qV5aFLLNaqWk3FTAWJwG6u6FfEOUNU',
    appId: '1:19038222441:web:f2898494151fb7105dcaf8',
    messagingSenderId: '19038222441',
    projectId: 'shopping-1aa4b',
    authDomain: 'shopping-1aa4b.firebaseapp.com',
    storageBucket: 'shopping-1aa4b.firebasestorage.app',
    measurementId: 'G-NHL24M2XJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUcLAmx9VOTgG_wxlnQ-dfx91SFcsVsvo',
    appId: '1:19038222441:android:0c52fdebbb5aece75dcaf8',
    messagingSenderId: '19038222441',
    projectId: 'shopping-1aa4b',
    storageBucket: 'shopping-1aa4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKipPb_PY53jCBdm0GcApLQbItn0miA4k',
    appId: '1:19038222441:ios:54f524a7723c681d5dcaf8',
    messagingSenderId: '19038222441',
    projectId: 'shopping-1aa4b',
    storageBucket: 'shopping-1aa4b.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKipPb_PY53jCBdm0GcApLQbItn0miA4k',
    appId: '1:19038222441:ios:54f524a7723c681d5dcaf8',
    messagingSenderId: '19038222441',
    projectId: 'shopping-1aa4b',
    storageBucket: 'shopping-1aa4b.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG3qV5aFLLNaqWk3FTAWJwG6u6FfEOUNU',
    appId: '1:19038222441:web:446fc03a8817c9bd5dcaf8',
    messagingSenderId: '19038222441',
    projectId: 'shopping-1aa4b',
    authDomain: 'shopping-1aa4b.firebaseapp.com',
    storageBucket: 'shopping-1aa4b.firebasestorage.app',
    measurementId: 'G-ZM0E9FWVCF',
  );
}
